version: "3.7"

services:
  nginx:
    build: "./.docker/nginx"
    container_name: sound-crossing-nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: "./.docker/php"
    container_name: sound-crossing-app
    working_dir: /app
    volumes:
      - ".:/app"
      - "./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./storage/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: sound-crossing
      MYSQL_USER: root
      MYSQL_PASSWORD: rootroot
      MYSQL_ROOT_PASSWORD: rootroot
    container_name: sound-crossing-mysql

  redis:
    image: redis:5.0.5-alpine
    container_name: sound-crossing-redis
    ports:
      - "6379:6379"

  mailcatcher:
    image: schickling/mailcatcher
    container_name: sound-crossing-mailcatcher
    ports:
      - "1080:1080"